version: '3'
 
services:
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    container_name: bazaar_http
    networks:
    - bazaar-net
  front:
    build: ./ha-proxy
    image: bazaar/haproxy
    container_name: bazaar-haproxy_http
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bazaar
    networks:
      - bazaar-net
networks:
  bazaar-net:
    driver: bridge
