version: '3'
 
services:
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    container_name: bazaar_lobby_http
    ports:
     - "8084:80"
    networks:
    - bazaar-net
networks:
  bazaar-net:
    driver: bridge
