version: '3'
#volumes:
#  mysql_data:
#  mongo_data:
 
services:
  mongo:
    image: mongo
    env_file:
      - ./server/bazaar/.env
    volumes:
      - ./mongo_data:/data/db
    networks:
      - bazaar-net
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:514
        syslog-facility: local1
        tag: "docker-bazaar"
  nodechat:
    build:
       context: ./mysql
    container_name: nodechat
    volumes:    
     - ./mysql_data:/var/lib/mysql
     - ./misc:/bazaar/misc
    env_file:
      - ./server/bazaar/.env
    networks:
    - bazaar-net
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:514
        syslog-facility: local1
        tag: "docker-bazaar"
  bazaar:
    build: 
       context: ./
    container_name: bazaar
    volumes:
      - ./agents:/usr/agents
      - ./server:/usr/bazaar
    depends_on:
     - nodechat
    ports:
     - "8119:80"  # let outside world see 8119
    networks:
    - bazaar-net
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:514
        syslog-facility: local1
        tag: "docker-bazaar"
networks:
  bazaar-net:
    driver: bridge
